### ISSUE TITLE
Results for market1501

### ISSUE THREAD

**Issue by Edelbert** [kilsenp/triplet-reid-pytorch#1]
Hi guys. What about results for market1501?  I'm having hard time trying to reproduce your paper results using pytorch. 
@lucasb-eyer

**Comment by lucasb-eyer** [comment]
IIRC @kilsenp did reproduce our scores with this code.

@kilsenp: I recommend setting some time aside to add a quality README to this repo, including instructions and a table with scores you get with this code. A good readme on your repos is very important to get exposure. You could even upload some pre-trainned models to the repo.

**Comment by kilianyp** [comment]
Hi, 
yes, I could reproduce the results and get a similar result (mAP 69%). I will upload a better documentation by this week! @Edelbert

**Comment by Edelbert** [comment]
Thank you for sharing code anyway.  I was able to reproduce your paper results using your code. I'll check mine carefully.

**Comment by kilianyp** [comment]
@Edelbert okay great!
